spring:
  application:
    name: fileManager
  datasource:
    url: jdbc:mysql://localhost:3306/lojaDB
    username: app_user
    password: appuser123
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
    show-sql: false

server:
  port: 8080
